// Generated by WinRC2Be Beta 6 Build Jun 15 2002 (c) Copyright realtech-VR 2000 - 2002 - http://www.realtech-vr.com
#include "RWindow.h"
#include "RView.h"
#include "RApplication.h"
#include "resource.h"
int main(int, char**)
{	
	// Create an application instance
	RApplication myApplication;

	// Run the application looper
	myApplication.Run();
	return(0);
}
// RApplication constructor
RApplication::RApplication() : BApplication("application/x-vnd.Be-Sample")
{
	BWindow *pWindow = LoadResource(IDD_SETUP, 0);
	pWindow->Show();
}
