// Generated by WinRC2Be Beta 6 Build Jun 15 2002 (c) Copyright realtech-VR 2000 - 2002 - http://www.realtech-vr.com
#ifndef __RAPPLICATION__HH
#define __RAPPLICATION__HH
#include <Application.h>
class RApplication : public BApplication
{
public:
	RApplication();
};
#endif // __RAPPLICATION__HH
