// Generated by WinRC2Be Beta 8 Build Oct 20 2002 - http://www.realtech-vr.com
#include <InterfaceKit.h>

#include "RViewList.h"
#include "RBitmapLoader.h" // File provided with BEVSRC
#include "RView.h"
#include "afxres.h"
#include "resource.h"
// Caution ! BeOS is case sensitive on filenames!
const char *LoadIconResource(unsigned id)
{
		switch(id) { 
		case IDI_ICON1 : return "../common/v3xlogo.ico";
			default: return NULL;
		}
}
RViewList *LoadResourceView(unsigned id, void *param)
{
	switch(id) {
		case IDD_SETUP :
		{
			RViewList *pCurrent, *pFirst;
			pCurrent = pFirst = new RViewList(new RBitmapView( BRect(236, 112, 266, 142), "IDC_STATIC", B_FOLLOW_ALL, LoadIconResource(IDI_ICON1)), -1);
			pCurrent->ID = IDC_STATIC;
			{ BBox *b = new BBox( BRect(10, 10, 267, 114), "User setup"); b->SetLabel("User setup"); pCurrent->next = new RViewList(b, -1); } 
			pCurrent->next->ID = IDC_STATIC;
			pCurrent = pCurrent->next;
			pCurrent->next = new RViewList(new BMenuField( BRect(8, 28, 248, 48), "", NULL, new BPopUpMenu("IDC_COMBO1"), true), 1);
			pCurrent->next->ID = IDC_COMBO1;
			pCurrent = pCurrent->next;
			pCurrent->next = new RViewList(new BMenuField( BRect(8, 74, 248, 94), "", NULL, new BPopUpMenu("IDC_COMBO2"), true), 1);
			pCurrent->next->ID = IDC_COMBO2;
			pCurrent = pCurrent->next;
			 { BButton *_b = new BButton( BRect(0, 111, 75, 132), "IDC_BUTTON1", "Ok", new BMessage(IDC_BUTTON1), B_FOLLOW_ALL, B_WILL_DRAW | B_NAVIGABLE ); pCurrent->next = new RViewList(_b, 1); _b->MakeDefault(false); _b->SetEnabled(true);}
			pCurrent->next->ID = IDC_BUTTON1;
			pCurrent = pCurrent->next;
			{ BStringView *_b = new BStringView( BRect(94, 120, 224, 132), "IDC_STATIC", "(c) realtech VR 1994-2001", B_FOLLOW_ALL, B_WILL_DRAW); _b->SetAlignment(B_ALIGN_LEFT); pCurrent->next = new RViewList(_b, 1); }
			pCurrent->next->ID = IDC_STATIC;
			pCurrent = pCurrent->next;
			{ BStringView *_b = new BStringView( BRect(218, 15, 252, 27), "IDC_STATIC", "Driver", B_FOLLOW_ALL, B_WILL_DRAW); _b->SetAlignment(B_ALIGN_LEFT); pCurrent->next = new RViewList(_b, 1); }
			pCurrent->next->ID = IDC_STATIC;
			pCurrent = pCurrent->next;
			{ BStringView *_b = new BStringView( BRect(196, 57, 252, 69), "IDC_STATIC", "Resolution", B_FOLLOW_ALL, B_WILL_DRAW); _b->SetAlignment(B_ALIGN_LEFT); pCurrent->next = new RViewList(_b, 1); }
			pCurrent->next->ID = IDC_STATIC;
			pCurrent = pCurrent->next;
			pCurrent->next = 0;
			return pFirst;
		}
		default:
		return 0;
	}
}
